Determina y corrige el/los error/errores que provoca que el fichero XML no sea v√°lido respecto
al ejemplo-agenda.dtd:

<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf)>
<!ATTLIST persona id #REQUIRED?>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "ejemplo-agenda.dtd">
<agenda>
    <persona>
        <nombre>Ricardo Borriquero</nombre>
        <tlf>951345678</tlf>
    </persona>
    <persona>
        <nombre>Eva Risto</nombre>
        <tlf>955837659</tlf>
    </persona>
</agenda>

<!DOCTYPE agenda
[
	<!ELEMENT agenda (persona)+>
	<!ELEMENT persona (nombre, tlf)>
	<!ATTLIST persona id #CDATA>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT tlf (#PCDATA)>
]